# Generated by Django 3.0.4 on 2020-03-15 21:28

import awards.models
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('project_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('description', models.TextField()),
                ('live_link', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awardproject', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, awards.models.CrudMethods),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('content', models.IntegerField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awardprojectrating', to='awards.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awardrating', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, awards.models.CrudMethods),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('profile_bio', models.TextField()),
                ('contact_info', models.EmailField(max_length=254)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awardprofile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, awards.models.CrudMethods),
        ),
    ]
